[profile.release]
panic = 'unwind'

[profile.dev]
split-debuginfo = "unpacked"

[workspace]
members = [
    'parachain',
    'runtime/*',
    'pallets/carbon-credits',
    'pallets/carbon-credits-pool',
    'primitives'
]
exclude = ['rpc']
