[profile.release]
panic = 'unwind'

[profile.dev]
split-debuginfo = "unpacked"

[workspace]
members = [
    'parachain',
    'runtime/*',
    'pallets/vcu',
    'pallets/vcu-pools',
    'primitives'
]
exclude = ['rpc']
